/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/media/torus_dan.glb --transform 
Files: public/media/torus_dan.glb [1.53MB] > ./public/media/torus_dan.glb
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Model(props) {
  const { nodes, materials } = useGLTF('/torus_dan.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Retopo_Cube001.geometry} material={materials['Dispersed Glass.003']} position={[-0.099, -0.073, 1.145]} rotation={[-1.148, 0.732, 1.807]} scale={173.33} />
    </group>
  )
}

useGLTF.preload('/torus_dan-transformed.glb')
